name: flutter_model_gen

description: A CLI tool that generates null-safe Dart models from REST API JSON responses.

version: 1.1.2

repository: https://github.com/o-Rushi-o/flutter_model_gen

issue_tracker: https://github.com/o-Rushi-o/flutter_model_gen/issues

topics:
  - dart
  - flutter
  - json
  - code-generation
  - model-generator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.6.0

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0

executables:
  flutter_model_gen: flutter_model_gen